spring:
  application:
    name: PacientesServico
  r2dbc:
    url: r2dbc:pool:postgresql://postgres:postgres@localhost:5432/register_service
    password: postgres
    username: postgres

  webflux:
    base-path: /register-service
